### ISSUE TITLE
Add signals for various events

### ISSUE THREAD

**Issue by ArthaTi** [Samerion/Fluid#13]
Should use `std.signals` probably. This would help prevent potential issues with calling functions which require a draw, in order to defer them to the point where they can safely be called. An example of this would be `GluiScrollable.scrollEnd` and `GluiScrollable.scrollTo`

**Comment by Soaku** [comment]
Those signals should be primarily for bindings to events within the tree, eg. before/after resizing, drawing, taking input etc.
