### ISSUE TITLE
Glui label sizing is horribly stupid

### ISSUE THREAD

**Issue by ArthaTi** [Samerion/Fluid#26]
![image](https://user-images.githubusercontent.com/28842854/131250409-eaf345c8-1533-40d4-803d-25bb53e01310.png)

However, this issue is a bit tricky to fix, because the label would need to know parent's align direction to know what direction to expand in (horizontally for hspace, vertically for vspace). Because the idea is a node shouldn't know its parent, it's not really possible to make this work, unless the parent passed this value to the child — and that's a terrible option.

Here are other options:

* Re-introduce `textWrap` in `style` — Could work, but since this is layout-heavy, and the value is expected to be the same between styles, it would be better off being set in layout.
* Split `label` to `vlabel` and `hlabel` — This absolutely would work, and could give more control over text wrap to the user. Current `label` could be aliased to `vlabel` and marked as deprecated.
* Introduce inline mode (which is a thing that should eventually be done), where nodes can define a secondary draw call which would take 3 vectors (cursorPosition, lineEnd, lineStart), so text rendering would be managed by the frame — the issue would remain for regular `vspace` and `hspace` though. This would probably be the best replacement for a `richTextLabel`, though.

Currently I'm most supportive of the second option, but I'm not sure how it'd work with said inline mode. Probably the direction would be ignored. And what about text rendering outside of labels? Wrap is managed by `Style` after all…

**Comment by Soaku** [comment]
btw it looks like `Style` moves multiple spaces to the end of the line… interesting.

**Comment by Soaku** [comment]
> btw it looks like `Style` moves multiple spaces to the end of the line… interesting.

Actually, this seems to be the reason for this to happen. The error message in the screenshot aligns properly as long as it doesn't feature multiple spaces.
